In [61]:
import pandas  as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

In [62]:
file=pd.read_csv('iphone.csv')
file

,IPHONES,MODEL,BASIC,BASIC PLUS,PLUS,PRO,PRO MAX,YEAR,PRIZE
0,IPHONE (1ST GEN),1,1,0,0,0,0,2007,30000
1,IPHONE 3G,3,1,0,0,0,0,2008,31000
2,IPHONE 3GS,3,0,1,0,0,0,2010,35000
3,IPHONE 4,4,1,0,0,0,0,2011,34500
4,IPHONE 4S,4,0,1,0,0,0,2011,44500
5,IPHONE 5,5,1,0,0,0,0,2012,45500
6,IPHONE 5C,5,0,1,0,0,0,2013,41900
7,IPHONE 5S,5,0,0,1,0,0,2013,53500
8,IPHONE 6,6,1,0,0,0,0,2014,53500
9,IPHONE 6 PLUS,6,0,0,1,0,0,2014,62500
10,IPHONE 6S,6,0,1,0,0,0,2015,62000
11,IPHONE 6S PLUS,6,0,0,1,0,0,2015,72000
12,IPHONE SE,7,0,1,0,0,0,2016,39000
13,IPHONE 7,7,1,0,0,0,0,2016,60000
14,IPHONE 7 PLUS,7,0,0,1,0,0,2016,72000
15,IPHONE 8,8,1,0,0,0,0,2017,64000
16,IPHONE 8 PLUS,8,0,0,1,0,0,2017,73000
17,IPHONE X,10,1,0,0,0,0,2017,89000
18,IPHONE XR,10,1,0,0,0,0,2018,76900
19,IPHONE XS,10,0,0,0,1,0,2018,99900
20,IPHONE XS MAX,10,0,0,0,0,1,2018,109900
21,IPHONE 11,11,1,0,0,0,0,2019,64900
22,IPHONE 11 PRO,11,0,0,0,1,0,2019,99900
23,IPHONE 11 PRO MAX,11,0,0,0,0,1,2019,109900
24,IPHONE SE,11,0,1,0,0,0,2020,42500
25,IPHONE 12 MINI,12,1,0,0,0,0,2020,69900
26,IPHONE 12,12,1,0,0,0,0,2020,79900
27,IPHONE 12 PRO,12,0,0,0,1,0,2020,119900
28,IPHONE 12 PRO MAX,12,0,0,0,0,1,2020,129900
29,IPHONE 13,13,1,0,0,0,0,2021,79900
30,IPHONE 13 MINI,13,1,0,0,0,0,2021,69900
31,IPHONE 13 PRO,13,0,0,0,1,0,2021,119900
32,IPHONE 13 PRO MAX,13,0,0,0,0,1,2021,129900
33,IPHONE 14,14,1,0,0,0,0,2022,79900
34,IPHONE 14 PLUS,14,0,0,1,0,0,2022,89900
35,IPHONE 14 PRO,14,0,0,0,1,0,2022,129900
36,IPHONE 14 PRO MAX,14,0,0,0,0,1,2022,139900
37,IPHONE 15,15,1,0,0,0,0,2023,79900
38,IPHONE 15 PLUS,15,0,0,1,0,0,2023,89900
39,IPHONE 15 PRO,15,0,0,0,1,0,2023,134900
40,IPHONE 15 PRO MAX,15,0,0,0,0,1,2023,159900
41,IPHONE 16,16,1,0,0,0,0,2024,79900
42,IPHONE 16 PLUS,16,0,0,1,0,0,2024,89900
43,IPHONE 16 PRO,16,0,0,0,1,0,2024,119900
44,IPHONE 16 PRO MAX,16,0,0,0,0,1,2024,144900
45,IPHONE 16 E,16,0,1,0,0,0,2025,59900
46,IPHONE 17,17,1,0,0,0,0,2025,82900
47,IPHONE AIR,17,0,1,0,0,0,2025,119900
48,IPHONE 17 PRO,17,0,0,0,1,0,2025,134900
49,IPHONE 17 PRO MAX,17,0,0,0,0,1,2025,149900
50,IPHONE 17 E,17,0,1,0,0,0,2026,64900

In [63]:
X=file[["MODEL","BASIC","BASIC PLUS","PLUS","PRO","PRO MAX","YEAR"]]
y=file["PRIZE"]

In [64]:
X_train,X_test,y_train,y_test=train_test_split(
    X,y,train_size=0.80,random_state=42
)

In [65]:
model=LinearRegression()

In [66]:
model.fit(X_train,y_train)

LinearRegression()

In [67]:
model.intercept_

np.float64(-3709287.001019275)

In [68]:
model.coef_

array([  1530.02486689, -20445.79814952, -24597.75635863, -10548.41313064,
        22662.93280379,  32929.03483499,   1873.36294589])

In [69]:
y=model.predict(X_test)

y

array([129542.93213622, 136405.64635464,  89837.58899569,  53525.11560463,
        67138.66685577, 119332.76869787,  64140.51136031, 129598.87072907,
        43720.1844836 ,  76224.03774455,  57677.07381373])

In [70]:
result=pd.DataFrame({
    'excel':y_test.values,
    'predict':y
})

result

     excel        predict
0   119900  129542.932136
1   159900  136405.646355
2    82900   89837.588996
3    39000   53525.115605
4    42500   67138.666856
5   119900  119332.768698
6    89000   64140.511360
7   129900  129598.870729
8    34500   43720.184484
9    69900   76224.037745
10   60000   57677.073814

In [71]:
from sklearn.metrics import root_mean_squared_error
mse=mean_squared_error(y_test,y)
rmse=root_mean_squared_error(y_test,y)
rsquare=r2_score(y_test,y)
rsquare

0.8700727819059056

In [72]:
a=float(input('ENTER THE MODEL NUMBER HERE :- '))
b=input('ENTER THE MODEL VARIANT(BASIC / BASIC PLUS / PLUS / PRO / PRO MAX) :- ')
c=float(input('ENTER THE YEAR :- '))

basic=0
basic_plus=0
plus=0
pro=0
pro_max=0

if b.upper()=='BASIC':
    basic=1
elif b.upper()=='BASIC PLUS':
    basic_plus=1
elif b.upper()=='PLUS':
    plus=1
elif b.upper()=='PRO':
    pro=1
elif b.upper()=='PRO MAX':
    pro_max=1
else:
    print('INVALID VARIANT !!')


prediction_input=model.predict([[
    a,basic,basic_plus,plus,pro,pro_max,c
]])

print("PREDICTED PRICE:", prediction_input[0])

PREDICTED PRICE: 150019.1976057822

c:\Users\Rdvel\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [73]:
import joblib
import os

print("curent folder",os.getcwd())

joblib.dump(model,r"F:\DATA SCIENCE-AHEMDABAD\MACHINE LEARNING - DHRUMIL SIR\iphone_price_prediction\iphone_model.pkl")
print('saved at:',os.path.abspath('iphone_model.pkl'))
print("MODEL SAVED SUCCESSFULLY")


# r means row string that will treat each special charactor as row string---used for url copy/paste.
#

curent folder f:\DATA SCIENCE-AHEMDABAD\MACHINE LEARNING - DHRUMIL SIR
saved at: f:\DATA SCIENCE-AHEMDABAD\MACHINE LEARNING - DHRUMIL SIR\iphone_model.pkl
MODEL SAVED SUCCESSFULLY