In [51]:
'''Download a dataset of mobile phone prices (with features like RAM, storage, camera MP, battery, brand, etc.) and 
fit a multiple linear regression model to predict the price using at least three features of your choice.'''
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

data=pd.read_csv('mobile_phone.csv')
data.head()

     Brand  RAM_GB  Storage_GB  Camera_MP  Battery_mAh  Price_INR
0  Samsung      12         256         12         5000      59200
1   Realme      12        1024         64         5000      90500
2     Oppo      16         128        200         3000      55300
3  OnePlus       8         256        108         5000      48300
4  OnePlus       8         512         50         5000      64700

In [52]:
x=data[['RAM_GB','Brand','Storage_GB']]

y=data['Price_INR']

x=pd.get_dummies(x, columns=['Brand'])     # this is used to convert string to float like indicators... easy for ml to understand... you can also give dtype=int to convert each brand to 0,1 category...

x_train,x_test,y_train,y_test=train_test_split(
    x,y,train_size=0.80,random_state=42
)

model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [53]:
y=model.predict(x_test)
y

array([75988.50109776, 36947.91258847, 42815.33452564, 70418.21511835,
       75988.50109776, 36677.95269121, 36947.91258847, 56182.74998994,
       33346.48380379, 39834.23626516, 49260.37718078, 64425.02468556,
       69675.93394985, 51768.40515354, 64393.53944935, 46889.08458156,
       33791.62901452, 78773.64408746, 89218.17447995, 40401.33212018,
       36726.45160589, 61047.28012904, 40625.01634834, 69675.93394985,
       70737.59183347, 53250.15064415, 75988.50109776, 73623.91551016,
       89355.91656206, 69675.93394985, 40162.66704317, 58080.97230144,
       34873.56553104, 48612.12157959, 43260.47973637, 86331.85080325,
       59514.21887737, 64393.53944935, 63472.88862217, 61047.28012904,
       97153.04604695, 75988.50109776, 68300.89343308, 69675.93394985,
       61988.32628518, 40401.33212018, 90840.47889905, 36502.76737774,
       34873.56553104, 69675.93394985, 67639.77914027, 46937.58349624,
       66519.6503759 , 40162.66704317, 47217.51535957, 51026.12398505,
       39733.05557817, 33521.66911726, 44713.55683714, 45093.48666268,
       37245.04854623, 38400.98968924, 76730.78226625, 36502.76737774,
       40401.33212018, 53530.08250747, 54933.47796878, 33346.48380379,
       36502.76737774, 90840.47889905, 33570.16803194, 33150.52853301,
       33346.48380379, 32975.34321954, 37006.38346922, 41186.13267894,
       84527.91175114, 53250.15064415, 43557.61569414, 43732.80100761,
       86390.321684  , 42947.81003288, 58080.97230144, 27107.92128237,
       47217.51535957, 46146.80341307, 61327.21199237, 58170.92841841,
       47217.51535957, 52519.47556332, 52787.80133898, 33478.95931102,
       78773.64408746, 51768.40515354, 46937.58349624, 59514.21887737,
       44002.76090487, 33346.48380379, 61327.21199237, 39882.73517984,
       36677.95269121, 66629.17219612, 73574.4986923 , 39882.73517984,
       43781.29992229, 36502.76737774, 37006.38346922, 51768.40515354,
       30264.20485632, 43557.61569414, 53530.08250747, 42667.87816955,
       33570.16803194, 48620.91082088, 45464.62724693, 57667.31232693,
       44713.55683714, 36947.91258847, 39834.23626516, 54686.21406645,
       33521.66911726, 62992.2262177 , 43557.61569414, 42815.33452564,
       41557.27326319, 39287.91036744, 54933.47796878, 57890.99655509,
       33346.48380379, 66629.17219612, 36726.45160589, 29994.24495906,
       29994.24495906, 46937.58349624, 47217.51535957, 52519.47556332,
       51026.12398505, 54956.17396371, 39882.73517984, 51768.40515354,
       52519.47556332, 51768.40515354, 44061.23178562, 72190.66893424,
       30322.67573707, 43732.80100761, 98004.84903566, 46937.58349624,
       63363.36680195, 55675.75913728, 72190.66893424, 39834.23626516,
       52459.37056097, 53250.15064415, 38400.98968924, 43781.29992229,
       57718.62095849, 46889.08458156, 83234.03811005, 45600.47751535,
       36502.76737774, 64393.53944935, 39287.91036744, 48612.12157959,
       46937.58349624, 46475.23419108, 50315.32805277, 57667.31232693,
       87684.1953251 , 33570.16803194, 95859.17240586, 45464.62724693,
       36947.91258847, 43557.61569414, 36947.91258847, 47217.51535957,
       46195.30232775, 60998.78121436, 53201.65172947, 69785.45577007,
       56627.89520067, 40162.66704317, 36726.45160589, 73952.34628817,
       45093.48666268, 76098.02291797, 89546.60525796, 67311.34836226,
       37006.38346922, 82301.06824566, 47217.51535957, 52519.47556332,
       26662.77607164, 44061.23178562, 72190.66893424, 58170.92841841,
       44002.76090487, 58112.45753766, 64393.53944935, 95530.74162785])

In [54]:
result=pd.DataFrame({
    'Original':y_test.values,
    'Prediction':y
})
result

     Original    Prediction
0       75900  75988.501098
1       29500  36947.912588
2       49900  42815.334526
3       78900  70418.215118
4       72200  75988.501098
..        ...           ...
195     58400  58170.928418
196     45200  44002.760905
197     56700  58112.457538
198     67200  64393.539449
199     90600  95530.741628

[200 rows x 2 columns]

In [ ]:
scr=r2_score(y_test,y)
scr

# Your model explains about 88% of the variation in mobile phone prices in your test data using RAM, Storage, and Brand.

0.8898670788234192

In [57]:
'''Display the regression coefficients and intercept from your model, and write a short comment on what 
each coefficient means in the context of mobile phones (e.g., how much price increases per extra GB of RAM).'''

model.coef_

#Coefficient = how much predicted y(price) changes when x increases by 1 unit, keeping other features constant.

array([ 1578.14178698,    55.11600247, 25133.34394207, -4379.92296461,
         170.96682936, -4659.85482794, -8039.82263004,  4078.3208131 ,
       -4708.35374262, -7594.67741932])

In [ ]:
'''Using the statsmodels or scikit-learn library, calculate the Variance Inflation Factor (VIF) for each feature in your dataset 
and identify if any features show signs of multicollinearity.<br><br><em><strong>Hint:</strong> VIF values above 5 or 10 
often indicate problematic multicollinearity.</em>'''