In [ ]:
'''WHAT IS HYPOTHESIS:--
-A hypothesis is a tentative statement or prediction that can be tested through research or experimentation.
-THIS MEANS ASSEMPTION.
-THIS HAS ONLY TWO OUTPUTS - SOMETHING CHANGE OR NOTHING CHANGE.
-NO OTHER OUTPUT IS POSSIBLE.
------------------------------------------------------------------------------------------
NULL HYPOTHESIS (H0) :---NOTHING CHANGE/LOSS. FAIR THING IS TAKEN MEANS NO EFFECT,NO DIFFERENCE,NO RELATIONSHIP,JUST NORMAL RANDOM DATA TAKEN.
1) Coin example

Suppose you want to check if a coin is fair.

Null hypothesis H0:

The coin is fair.
Meaning:

Probability of head = 0.5
Probability of tail = 0.5
-------------------------------------------------------------------------------------------
ALTERNATE HYPOTHESIS (H1,Ha) :-- SOMETHING CHANGE/PROFIT.SOMETHING HAS DONE TO DATA AND THAT IS NOT NORMAL/FAIR FOR FURTHER PROCESS.
-Alternative hypothesis is the opposite claim of the null hypothesis.
If null hypothesis says:
“Nothing special is happening / no effect / no difference”

then alternative hypothesis says:
“Something is happening / there is an effect / there is a difference”
-------------------------------------------------------------------------------------------'''

In [2]:
'''P-VALUES:-p-value tells us:
A p-value is the probability of observing results at least as extreme as the ones you got, assuming the null hypothesis is true.
| P-value | Interpretation                                               |
| ------- | ------------------------------------------------------------ |
| > 0.05  | Weak evidence against the null hypothesis; do not reject H₀. |
| ≤ 0.05  | Moderate evidence against H₀; often reject H₀.               |
| ≤ 0.01  | Strong evidence their is something done to H₀.               | (be carefull it is just doubt not 100% sure).

-----------------------------------------------------------------------------------------

P-VALUES BIG OR SMALL:--
HERE IF H0 IS TRUE MEANS We assume the “default / no special effect / no real change / no real difference” statement is true,
and then check whether our data looks normal under that assumption.

Imagine a dartboard.
🎯 Bullseye = expected result

If your dart lands exactly in the center (5 heads),
you wouldn't think,
"Something strange happened!"

You'd think,
"Yep, that's normal."
Since your observation is not unusual, the probability of getting it (or something similarly close to expectation) is high.

So, p-value is big.
-If the result is what the null hypothesis would normally produce, then p-value is big.
-If the result is very unusual under the null hypothesis, then p-value is low.
-------------------------------------------------------------------------------------------

How do we actually find the p-value?

-There are several methods.
Method 1: Using a Z-table
Suppose;
z = 2.00

NOW VALUE IS IF Z=2 IN Z TABLE IS 0.9772
THEN P-VALUE IN RIGHT - TAILER TEST = 1-0.9772=0.0228.

IF Z=2
Z-TABLE VALUE = 0.0228

THEN FOR LEFT TAILES TEST P-VALUE = 0.0228(SAME)

IF Z=2
Z-TABLE VALUE = 0.9772

THEN FOR 2-TAILED TEST P-VALUE = 2 * 0.0228 = 0.0456.
-------------------------------------------------------------------------------------
Why is it called a "probability value"?

Because it is literally a probability.

It always lies between:

0 and 1

Examples:

0.001
0.02
0.18
0.75
----------------------------------------------------------------------------------------
Does a smaller p-value mean stronger evidence?

Yes.

p-value	Meaning
0.50	Very weak evidence against H₀
0.20	Weak evidence
0.05	Borderline significance
0.01	Strong evidence against H₀
0.001	Very strong evidence against H₀
----------------------------------------------------------------------------------------
PERFECT BEST REAL-LIFE EXAMPLE:--

Think of it like a court trial ⚖️

Suppose:

H₀: The accused is innocent.
H₁: The accused is guilty.

The court starts by assuming innocence (just as hypothesis testing starts by assuming H₀ is true).

Now evidence is presented.

Case 1: Weak evidence

Imagine the evidence is weak.

There is a 70% chance that such evidence could appear even if the accused were innocent.

So,

p-value = 0.70

This means:

"This evidence is not unusual if the accused is innocent."

So the court says:

✅ We don't have enough evidence to reject innocence.

This is like failing to reject H₀.
----------------------------------------------------------------------------------------
ALWAYS TAKE LIKE THIS HOW MUCH PERCENT CHANCE IS IT TO BE ?
IF IT IS 30% MEANS 0.03 MEANS IT IS RARE MEANS SURPRISING SO REJECT H0.
IF IT IS 70% MEANS 0.07 MEANS IT IS LIKELY TO BE HAPPEN NOT SURPRISING SO GO WITH H0.'''

'P-VALUES:-p-value tells us:\nA p-value is the probability of observing results at least as extreme as the ones you got, assuming the null hypothesis is true.\n| P-value | Interpretation                                               |\n| ------- | ------------------------------------------------------------ |\n| > 0.05  | Weak evidence against the null hypothesis; do not reject H₀. |\n| ≤ 0.05  | Moderate evidence against H₀; often reject H₀.               |\n| ≤ 0.01  | Strong evidence their is something done to H₀.               | (be carefull it is just doubt not 100% sure).\n\n-----------------------------------------------------------------------------------------\n\nP-VALUES BIG OR SMALL:--\nHERE IF H0 IS TRUE MEANS We assume the “default / no special effect / no real change / no real difference” statement is true,\nand then check whether our data looks normal under that assumption.\n\nImagine a dartboard.\n🎯 Bullseye = expected result\n\nIf your dart lands exactly in the center (5 heads),\nyou wouldn\'t think,\n"Something strange happened!"\n\nYou\'d think,\n"Yep, that\'s normal."\nSince your observation is not unusual, the probability of getting it (or something similarly close to expectation) is high.\n\nSo, p-value is big.\n-If the result is what the null hypothesis would normally produce, then p-value is big.\n-If the result is very unusual under the null hypothesis, then p-value is low.\n-------------------------------------------------------------------------------------------\n\nHow do we actually find the p-value?\n\n-There are several methods.\nMethod 1: Using a Z-table\nSuppose;\nz = 2.00\n\nNOW VALUE IS IF Z=2 IN Z TABLE IS 0.9772\nTHEN P-VALUE IN RIGHT -TAILER TEST = 1-0.9772=0.0228.\n\nIF Z=2\nZ-TABLE VALUE = 0.0228\n\nTHEN FOR LEFT TAILES TEST P-VALUE = 0.0228(SAME)\n\nIF Z=2\nZ-TABLE VALUE = 0.9772\n\nTHEN FOR 2-TAILED TEST P-VALUE = 2 * 0.0228 = 0.0456.\n-------------------------------------------------------------------------------------\nWhy is it called a "probability value"?\n\nBecause it is literally a probability.\n\nIt always lies between:\n\n0 and 1\n\nExamples:\n\n0.001\n0.02\n0.18\n0.75\n----------------------------------------------------------------------------------------\nDoes a smaller p-value mean stronger evidence?\n\nYes.\n\np-value\tMeaning\n0.50\tVery weak evidence against H₀\n0.20\tWeak evidence\n0.05\tBorderline significance\n0.01\tStrong evidence against H₀\n0.001\tVery strong evidence against H₀\n----------------------------------------------------------------------------------------\n\nPERFECT BEST REAL-LIFE EXAMPLE:--\nThink of it like a court trial ⚖️\n\nSuppose:\n\nH₀: The accused is innocent.\nH₁: The accused is guilty.\n\nThe court starts by assuming innocence (just as hypothesis testing starts by assuming H₀ is true).\n\nNow evidence is presented.\n\nCase 1: Weak evidence\n\nImagine the evidence is weak.\n\nThere is a 70% chance that such evidence could appear even if the accused were innocent.\n\nSo,\n\np-value = 0.70\n\nThis means:\n\n"This evidence is not unusual if the accused is innocent."\n\nSo the court says:\n\n✅ We don\'t have enough evidence to reject innocence.\n\nThis is like failing to reject H₀.'

In [2]:
# EXAMPLE OF P-TYPE(P-VALUE) PROBABILITY-VALUE:-
import math

sample_mean = 54
population_mean = 50
sigma = 8            # Sigma means population standard deviation.It tells how spread out the data usually is.
n = 16               #  n means sample size ,,how many values are in your sample.
 
z = (sample_mean - population_mean) / (sigma / math.sqrt(n))   # z is the z-score. math.sqrt means square-root of (n).
print("z =", z)

p_value = 0.0455     #  p=2(1−Φ(∣z∣))    here that is standard deviation z-table for in (z) value.that z-table you have to search for google z-table values.
#  Φ(2.00)=0.9772 in z-table by google. 1-0.9772 = 0.0228*2 =0.0456
print("p-value =", p_value)

if p_value < 0.05:
    print("Reject H0")
else:
    print("Do not reject H0")

z = 2.0
p-value = 0.0455
Reject H0

In [ ]:
'''TYPE -1 ERROR:-Rejecting a true null hypothesis
-You rejected the null hypothesis even though the null hypothesis was actually true.
You say:
“Something is wrong / something changed”

but in reality:
"nothing was wrong".

EXAMPLE:---Suppose the coin is actually fair in real life.
But after tossing, you get a strange result and you say:
“No, this coin is not fair”

So you reject H0.

But the truth was:
coin was fair.

Then this is a Type 1 error.
--------------------------------------------------------------------------------------------
TYPE -2 ERROR:-
-You do not reject the null hypothesis even though the null hypothesis is actually false.

You say:
“Nothing is wrong / no effect”

but in reality:
something actually is wrong / there is an external-effect.
EXAMPLE:-Suppose in reality the coin is not fair.

But after testing, you say:
“Coin is fair”

or

“I do not reject H0".
Then this is Type 2 error.'''

In [ ]:
'''the test depends on the problem type:-
1) Z-test

Use when:

-testing a mean
-population standard deviation(VARIANCE SQUARE-ROOT) σ is known

Example:

H₀: mean height = 170
σ known = 10

Then use z-test.
-------------------------------------------------------------------------
2) T-test

Use when:

testing a mean
but population standard deviation is not known

Example:

H₀: mean marks = 50
you only have sample data
no population SD given

Then use t-test.
--------------------------------------------------------------------------
3) Chi-square test

Use when data is counts / categories

Example:

40 people choose tea, coffee, juice
want to know if all choices are equally liked

Then chi-square.
---------------------------------------------------------------------------
4) ANOVA

Use when comparing more than 2 means

Example:

compare average marks of Class A, B, C

Then ANOVA.
---------------------------------------------------------------------------

IN SHORT:--

| Situation                         | Test           |
| --------------------------------- | -------------- |
| Mean test + population SD known   | **Z-test**     |
| Mean test + population SD unknown | **T-test**     |
| Counts / categories               | **Chi-square** |
| Compare 3+ means                  | **ANOVA**      |
'''

In [ ]:
'''HOW TO DECIDE WHICH TEST IT IS:-

| Words in the question                                         | Alternative Hypothesis (H₁) | Test Type        |
| ------------------------------------------------------------- | --------------------------- | ---------------- |
| **differs from**, **not equal to**, **is different from**     | μ ≠ μ₀                      | **Two-tailed**   |
| **greater than**, **more than**, **higher than**, **exceeds** | μ > μ₀                      | **Right-tailed** |
| **less than**, **smaller than**, **lower than**, **below**    | μ < μ₀                      | **Left-tailed**  |
'''

In [4]:
# COMPLETE Z-TEST PROGRAM PERFORMING 2-TAILED TEST USING P-VALUE APPROUCH:--

from scipy import stats
import math

sample_mean = 165
population_mean = 170
population_std = 10                # this is standard deviation ,,this tell us how-much is our data spread.
sample_size = 50
alpha = 0.05

# Z-Test  (Two Tailed)
# Calculate Z_SCORE

z_score = (sample_mean-population_mean)/(population_std/math.sqrt(sample_size))

# Calculate p-value
#In a two-tailed test, we don't care whether the test statistic is positive or negative. We only care how far it is from 0.

p_value = 2 * (1-stats.norm.cdf(abs(z_score)))              #stats.norm.cdf() always calculate (area to the left). Abs removes negative sign.cdf=Cumulative Distribution Function

print("Z_Score:",z_score)
print("p_value:",p_value)

if p_value<alpha:
  print("Reject the Null Hypothesis")
else:
  print("Fail to reject the Null Hypothesis")

Z_Score: -3.5355339059327378
p_value: 0.00040695201744500586
Reject the Null Hypothesis

In [5]:
#COMPLETE Z-TEST PROGRAM PERFORMING RIGHT-TAILED TEST USING P-VALUE APPROUCH:--

sample_mean = 72
population_mean = 75
population_std = 8
sample_size = 36
alpha = 0.05


# Z-Test  (One Tailed)

# Calculate Z_SCORE

z_score = (sample_mean-population_mean)/(population_std/math.sqrt(sample_size))

# Calculate p-value

p_value = 1-stats.norm.cdf(abs(z_score))              # 1-stats.norm.cdf===Area to the right of z

print("Z_Score:",z_score)
print("p_value:",p_value)

if p_value<alpha:
  print("Reject the Null Hypothesis")
else:
  print("Fail to reject the Null Hypothesis")

Z_Score: -2.25
p_value: 0.012224472655044671
Reject the Null Hypothesis

In [ ]:
'''This is why, in hypothesis testing, we often use:

Left-tailed test: stats.norm.cdf(z)
Right-tailed test: 1 - stats.norm.cdf(z)
Two-tailed test: 2 * (1 - stats.norm.cdf(abs(z)))

These three formulas cover the most common Z-test p-value calculations.'''

In [7]:
def hypothesis_result(p_value,alpha):
  if p_value<alpha:
    print("Reject Null Hypothesis")
  else:
    print("Fail to reject Null Hypothesis")

In [ ]:
'''T-TEST FULL EXPLANATION:---

ttest_1samp()--One Sample:---One sample vs one known population mean.

-----------------------------------------------------------------------------------
ttest_rel()--Related (Paired):----Used when the observations are related.
Examples:

Weight before and after diet
Blood pressure before and after medicine
Student marks before and after coaching
-----------------------------------------------------------------------------------
ttest_ind()--independent:--Used when the two groups are completely different.
example:-
boys = [70, 75, 80, 78]
girls = [65, 68, 70, 69]
'''

In [8]:
# T-TEST FOR ONE SAMPLE:---

sample_data = [4.9,5.1,4.8,5.0,5.2,4.9,5.0,5.1,5.0,4.8]
population_mean = 5.0
sample_size = 10
alpha=0.05

# T-test (One Sample Test)

t_statistic,p_value = stats.ttest_1samp(sample_data,population_mean)   # ttest_1samp() is a built-in SciPy function that performs a One-Sample T-Test.  Stats.ttest_1samp(sample_data,population_mean) this always return two values one is t-test and other is p-value.

print(t_statistic)
print(p_value)
hypothesis_result(p_value,alpha)

-0.4803844614152726
0.6424151377207816
Fail to reject Null Hypothesis

In [4]:
# T-TEST FOR RELATED PAIRED:--

before = [80,85,78,90,95,88,76,82]
after =  [78,84,76,88,94,87,74,81]

sample_size = 8
alpha = 0.05

t_statistic,p_value = stats.ttest_rel(before,after)

print(p_value)
hypothesis_result(p_value,alpha)

9.58459057192917e-05
Reject Null Hypothesis

In [9]:
#T-TEST FOR INDEPENDENT :---

boys = [70, 75, 80, 78]
girls = [65, 68, 70, 69]

t_statistics,p_value=stats.ttest_ind(boys,girls)

print(t_statistics)
print(p_value)
hypothesis_result(p_value,alpha)

3.1917517372037985
0.018794702472336982
Reject Null Hypothesis

In [10]:
import pandas as pd
import scipy.stats as stats

data = {'Sales':[200,220,215,300,305,290,180,185,190,260,270,265],
        'Channel':['TV','TV','TV','Social_Media','Social_Media','Social_Media','TV','Radio','Radio','Radio','Social_Media','Radio']}
df = pd.DataFrame(data)
df

    Sales       Channel
0     200            TV
1     220            TV
2     215            TV
3     300  Social_Media
4     305  Social_Media
5     290  Social_Media
6     180            TV
7     185         Radio
8     190         Radio
9     260         Radio
10    270  Social_Media
11    265         Radio

In [13]:
# ANOVA TEST FOR INDEPENDENT MORE THAN 2 GROUPS.

annova_result=stats.f_oneway(df[df['Channel']=='TV']['Sales'],
                             df[df['Channel']=='Social_Media']['Sales'],
                             df[df['Channel']=='Radio']['Sales'])  # this means :- select rows where channel is TV and from those row select only sales column.

# stats.f_oneway() performs a One-Way ANOVA test.It compares the means of three or more independent groups.groups are :-tv sales,social media,radio sales

print(annova_result.statistic)
print(annova_result.pvalue)
hypothesis_result(annova_result.pvalue,alpha)

10.218909710391822
0.00483076517098152
Reject Null Hypothesis

In [15]:
import pandas as pd
import scipy.stats as stats
from scipy.stats import chi2_contingency

data = {'Credit Card':[30,50],
        'Paypal':[20,40],
        'Cash':[50,30]}

df = pd.DataFrame(data,index=['North','South'])
df

       Credit Card  Paypal  Cash
North           30      20    50
South           50      40    30

In [18]:
# CHI-SQUARE TEST FOR COUNTS/CATEGORICAL DATA:--

alpha = 0.05
chi2,p,dof,expected = chi2_contingency(df)  # here function returns 4 values. chi2= It tells you how different the observed values are from the expected values. p is for p_value. dof means Degree Of Freedom.dof=(row-1) x (column-1). Expected :-These are the expected frequencies if the null hypothesis is true.
# when you are using chi2_contingency(df) you have to every time take this 4 variables chi2,p,dof,expected.

print(p)
hypothesis_result(p_value,alpha)

0.0005608196906689444
Reject Null Hypothesis

In [19]:
# Chi-Square Goodness of Fit Test:---

observed = [25,45,30]

expected_proportions = [0.3,0.5,0.2]   # this means you expected observed a(25) to be 30%,b(45) to be 50% and c(30) to be 20%. Total is 0.3 + 0.5 + 0.2 = 1.0

expected = [x * sum(observed) for x in expected_proportions]  #this means x*(25+45+30 = 100) for x in (0.3,0.5,0.2) that means 0.3*100,0.5*100,0.2*100.so expected = [30,50,20]

chi2,p = stats.chisquare(f_obs=observed,f_exp=expected)   # here (f_observed and f_expected is given) 

print(p)
hypothesis_result(p_value,alpha)

0.0421438435092764
Reject Null Hypothesis