In [7]:
import pandas as pd
import numpy as np

data={'date':['2024-01-01','2024-02-15','2024-03-10']}
df=pd.DataFrame(data)   # here date is in string which will not help in doing any further process we need it in original date.
df
df['ori_date']=pd.to_datetime(df['date'])
df

         date   ori_date
0  2024-01-01 2024-01-01
1  2024-02-15 2024-02-15
2  2024-03-10 2024-03-10

In [13]:
# USING .DT.YEAR/DT.MONTH.DT.DAY

import pandas as pd
import numpy as np

data={'date':['2024-01-01','2024-02-15','2024-03-10']}
df=pd.DataFrame(data)
df['date']=pd.to_datetime(df['date'])
df['year']=df['date'].dt.year
df['month']=df['date'].dt.month
df['day']=df['date'].dt.day
df

        date  year  month  day
0 2024-01-01  2024      1    1
1 2024-02-15  2024      2   15
2 2024-03-10  2024      3   10

In [19]:
# pd.date_range(start,end,freq=('D','ME','YE'))
# pd.date_range() is used to generate a sequence of dates automatically.

import pandas as pd
import numpy as np

data=pd.date_range(start='2024-01-01',end='2024-12-01',freq='ME')
#data = pd.date_range(start='2024-01-01', periods=10)   # periods means till that given periods.
print(data)

DatetimeIndex(['2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
               '2024-09-30', '2024-10-31', '2024-11-30'],
              dtype='datetime64[ns]', freq='ME')