In [ ]:
'''pd.merge:-
pd.merge() is used to combine two DataFrames based on a common column, just like SQL JOINs.
SYNTAX :--

pd.merge(df1, df2, on='common_column', how='inner')

df1 → First DataFrame
df2 → Second DataFrame
on → Common column used for matching
how → Type of join (inner, left, right, outer)

outer:---Keeps everything from both DataFrames.
right:--Keeps all rows from the right DataFrame (sales).
left:---Keeps all rows from the left DataFrame (customers).'''

In [4]:
import pandas as pd

customers=pd.DataFrame({
    'customer_ID':[1,2,3],
    'name':['aman','priya','rahul']
})

sales=pd.DataFrame({
    'customer_ID':[1,2,4],
    'amount':[500,700,300]
})

customers,sales
pd.merge(customers,sales,how='inner',on='customer_ID')   # how='inner' means only that entry which is common on both. on=customer_ID means which column should be used as the common key to match rows between the two DataFrames.
# you can give composite key also here.
# if not given how then its ok, bydefault it is inner only.

   customer_ID   name  amount
0            1   aman     500
1            2  priya     700

In [ ]:
'''CONCATENATION AND DATA REPETATION:---
1. Concatenation (pd.concat()):--
-Concatenation means simply sticking DataFrames together, either row-wise or column-wise.
-It does not match values like merge().
MERGE CAN COMBINE ONLY TWO DATAFRAMES.
CONCATE MERGE MORE THAN 2.
SYNTAX:-
PD.CONCATE([DF1,DF2],AXIS=1)  # 1 FOR COLUMN.
PD.CONCATE([DF1,DF2,DF3],AXIS=1)'''

In [1]:
import pandas as pd

df1 = pd.DataFrame({
    'name':['Aman','Priya']
})

df2 = pd.DataFrame({
    'name':['Rahul','Neha']
})

pd.concat([df1, df2])  #Concatenation means simply sticking DataFrames together, either row-wise or column-wise.

    name
0   Aman
1  Priya
0  Rahul
1   Neha

In [ ]:
'''concat() = "Glue tables together"
merge() = "Match rows using a common key"
Data repetition = Happens when one key matches multiple rows during a merge'''