In [ ]:
'''An outlier is a value that is very different from the rest of the data.
EXAMPLE:-
a=[22, 25, 24, 23, 26, 120]
Here, 120 is an outlier because all the other ages are around 22–26.'''

In [4]:
import numpy as np

ages =np.array([22, 25, 24, 23, 26])
print(ages.mean())

24.0

In [5]:
ages=np.array([22,24,23,22,120])
print(ages.mean())  # this is how outliers affect the mean.

42.2

In [18]:
# EXAMPLE OF OUTLIER:--
import pandas as pd
import numpy as np

salary = np.array([20000, 22000, 21000, 23000, 24000, 25000, 150000])

df = pd.DataFrame({'SALARY':salary})

print(df)
print('\nMEAN :--',salary.mean())     #The outlier is pulling the average upward.

   SALARY
0   20000
1   22000
2   21000
3   23000
4   24000
5   25000
6  150000

MEAN :-- 40714.28571428572

In [ ]:
'''HANDLING DUPLICATE AND OUTLIERS:-
-DUPLICATE RECORDS.
SYNTAX:-
DROP_DUPLICATES()

In [7]:
# DROPING DUPLICATE:-
import pandas as pd
import numpy as np

a ={'name':['aman','vijay','mohit','jay','veeru','aman','jivan'],
    'salary':[20000, 22000, 21000, 23000, 24000, 20000, 150000]
   }

df = pd.DataFrame(a)
df
df.drop_duplicates()

    name  salary
0   aman   20000
1  vijay   22000
2  mohit   21000
3    jay   23000
4  veeru   24000
6  jivan  150000

In [12]:
# How to find outliers quickly?
import pandas as pd
salary =list(np.random.randint(20000,80000,491))
salary+=[150000, 180000, 220000, 250000, 300000,350000, 400000, 450000, 500000, 750000]
df = pd.DataFrame({'salary':salary})
print(df.describe())

q1=df['salary'].quantile(0.25)   # Pandas looks for an exact match:'salary'
print('\nvalue of q1:-',q1)
q3=df['salary'].quantile(0.75)   # quantile() is used to find the value below which a certain percentage of data falls.
print('\nvalue of q3:-',q3)

IQR=q3-q1

lower=q1-1.5*IQR       # Any value outside these limits is considered an outlier.
upper=q3+1.5*IQR

print('\nLOWER :-',lower)
print('\nUPPER',upper)

print(df[(df['salary']<lower) | (df['salary']>upper)])  # df['salary']<lower is condition and if true df[...] returns only the rows where the final result is True,,,,  | means OR.

              salary
count     501.000000
mean    54835.714571
std     52207.137755
min     20057.000000
25%     33608.000000
50%     47998.000000
75%     64931.000000
max    750000.000000

value of q1:- 33608.0

value of q3:- 64931.0

LOWER :- -13376.5

UPPER 111915.5
     salary
491  150000
492  180000
493  220000
494  250000
495  300000
496  350000
497  400000
498  450000
499  500000
500  750000

In [ ]:
'''Z-SCORE CONCEPT:-
STANDARD DEVIATION:-SET OF VALUES WHICH HAS IT MEAN FAR AWAY FROM THAT ELEMENT.
Z_SCORE=(SALES-MEAN)/STD

VALUES GREATER THAN 3 FOR Z_SCORE IS CONSIDER BAD.'''

In [ ]:
# Z-SCORE:-

In [42]:
# COLUMN OPERATIONS & DATA TRANSFORMATIONS:-
# COLUMN OPERATIONS MEANS :-- ADDIND COLUMN TO DF.
import pandas as pd

data={'product':['pen','notebook','marker'],
      'price':[10,20,50],
      'qty':[100,40,60]
     }
df=pd.DataFrame(data)
df
#df['revenue']=df['price']*df['qty']  # like this you can add column.
df
df['taxable_amount']=(df['price']* 1.10-df['price']) *df['qty']
df
#df['tax'] = df['price'].map(lambda x: x * 1.10)
df

    product  price  qty  taxable_amount
0       pen     10  100           100.0
1  notebook     20   40            80.0
2    marker     50   60           300.0