In [ ]:
'''PIVOT:---
In pandas, a pivot is used to reshape data.
It converts values from rows into columns,making the data easier to summarize and analyze.
SYNTAX:-

DF.PIVOT(INDEX,COLUMNS,VALUES)

In [6]:
import pandas as pd

df2 = pd.DataFrame({
    'City':['Rajkot','Rajkot','Ahmedabad','Ahmedabad'],
    'Product':['Mobile','Laptop','Mobile','Laptop'],
    'Sales':[50,30,70,40]
})
df2.pivot(index='Product',columns='City',values='Sales')
df2

        City Product  Sales
0     Rajkot  Mobile     50
1     Rajkot  Laptop     30
2  Ahmedabad  Mobile     70
3  Ahmedabad  Laptop     40

In [7]:
import pandas as pd
import numpy as np

data={'month':['feb','feb','jan','jan','hh','jj'],
      'product':['a','b','a','b','b','b'],
      'sales':[100,200,150,250,150,250]
     }
df=pd.DataFrame(data)
df
df2=df.pivot(index='month',columns='product',values='sales')
df2   # PIVOT MAKES A NEW DF .THEN WE CAN APPLY ANYTHING TO IT.

product      a      b
month
feb      100.0  200.0
hh         NaN  150.0
jan      150.0  250.0
jj         NaN  250.0

In [ ]:
'''pivot() works only when each combination of index and columns is unique.

For example:'''

In [9]:
import pandas as pd
import numpy as np

data={'month':['feb','feb','jan','jan'],
      'product':['a','b','b','b'],   # GIVING JAN 2 TIMES B.THAT MEANS DUPLICATE.
      'sales':[100,200,150,250]
     }
df=pd.DataFrame(data)
df
df2=df.pivot(index='month',columns='product',values='sales')
df2   # PIVOT cannot handle duplicate value so it will give error.

ValueError: Index contains duplicate entries, cannot reshape

In [8]:
import pandas as pd
import numpy as np

data={'month':['feb','feb','jan','jan'],
      'product':['a','b','b','b'],
      'sales':[100,200,150,250]
     }
df=pd.DataFrame(data)

df3=df.pivot_table(index='month',columns='product',values='sales',aggfunc='sum')  
# aggfunc stands for Aggregation Function. It tells pivot_table() what to do when multiple values exist for the same group.
df3   # pivot_table used to handle extra value it will sum the values.jan has two b so it will add that similar values.

product      a      b
month
feb      100.0  200.0
jan        NaN  400.0

In [ ]:
'''DRAW-BACK OF PIVOT IT CAN ONLY FETCH THE DATA BUT IT CANNOT APPLY OPERATIONS LIKE ADD,SUB LIKE THAT TO ELEMENTS.'''